version: "3.9"

services:
  wordpress:
    build: 
      context: ./docker/app
      args: 
        - PHP_VERSION=8.1
    depends_on:
      - database
    networks:
      - tagsforhope
    volumes:
      - ./src:/var/app

  dashboard:
    build: 
      context: ./docker/app
      args: 
        - PHP_VERSION=7.4
    depends_on:
      - database
    networks:
      - tagsforhope
    volumes:
      - ./src:/var/app

  warranty:
    build: 
      context: ./docker/app
      args: 
        - PHP_VERSION=8.1
    depends_on:
      - database
    networks:
      - tagsforhope
    volumes:
      - ./src:/var/app

  apache:
    build: ./docker/apache
    hostname: tagsforhope.loc
    depends_on:
      - wordpress
      - dashboard
    networks: 
      tagsforhope:
        aliases:
          - dashboard.tagsforhope.loc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/app

  database:
    image: mysql:8.0
    networks:
      - tagsforhope
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./docker/database:/var/lib/mysql

networks:
  tagsforhope:
    driver: bridge